require 'magic_scopes/base'
require 'magic_scopes/scope_generators/base'
require 'magic_scopes/scope_generators/boolean'
require 'magic_scopes/scope_generators/num'
require 'magic_scopes/scope_generators/string'
require 'magic_scopes/scope_generators/float'
require 'magic_scopes/scope_generators/association'
require 'magic_scopes/scope_generators/state'
require 'magic_scopes/version'
require 'magic_scopes/railtie' if defined?(Rails)
